site_name: Test
repo_url: https://jeffwhite530.github.io/actions-test
site_url: https://github.com/jeffwhite530/actions-test
theme: readthedocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - About: index.md
