apiVersion: v2
name: slurm-cluster
description: A Helm chart for deploying and managing Slurm HPC clusters on Kubernetes
type: application
dependencies:
  - name: ingress-nginx
    version: "4.9.0"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingressNginx.enabled
  - name: metrics-server
    version: "3.11.0"
    repository: https://kubernetes-sigs.github.io/metrics-server/
    condition: slurmd.deployment.autoscaling.enabled
version: 0.1.0
appVersion: "24.11.0.1"
