apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "slurm-cluster.fullname" . }}-node-watcher
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
