apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm-cluster.fullname" . }}-mariadb-root
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
type: Opaque
data:
  {{- if not (hasKey .Values "secrets") }}
  {{- fail "Error: .Values.secrets is required but not found in values.yaml" }}
  {{- end }}
  {{- if not (hasKey .Values.secrets "mariadb") }}
  {{- fail "Error: .Values.secrets.mariadb configuration is required but not found in values.yaml" }}
  {{- end }}
  {{- if not (and (hasKey .Values.secrets.mariadb "username") (hasKey .Values.secrets.mariadb "password")) }}
  {{- fail "Error: Required configuration missing. Please ensure .Values.secrets.mariadb.username and .Values.secrets.mariadb.password are set in values.yaml" }}
  {{- end }}
  username: {{ .Values.secrets.mariadb.username | toString | b64enc | quote }}
  password: {{ .Values.secrets.mariadb.password | toString | b64enc | quote }}