---
# Ansible playbook to set up web application environment
- name: Web Application Setup
  hosts: webservers
  become: no

  vars:
    app_path: /var/www/app

  tasks:
    - name: Create log directory
      ansible.builtin.file:
        path: /var/log/app
        state: directory
        mode: "0755"
        owner: www-data
        group: www-data
