---
# Missing metadata like author, description
- hosts: webservers
  vars:
    app_path: /var/www/app

    # Unsafe file permissions
    - name: Create log directory
      file:
        path: /var/log/app
        state: directory
        mode: 640


