name: Run Code Linters

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Helm lint
        run: |
          if [ -d "./helm" ]; then
            for chart in ./helm/*/; do
              if [ -f "$chart/Chart.yaml" ]; then
                echo "Linting chart: $chart"
                helm lint "$chart"
              fi
            done
          else
            echo "No helm directory found"
          fi

      - name: Run super-linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Enable specific linters
          VALIDATE_ANSIBLE: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_YAML: true
